import { ReactComponent as PersonIconSvg } from "./person.svg";
import { ReactComponent as SearchIconSvg } from "./search.svg";
import { ReactComponent as NotificationsIconSvg } from "./notifications.svg";
import { ReactComponent as ChatIconSvg } from "./chat.svg";
import { ReactComponent as MoreVertIconSvg } from "./more-vert.svg";
import { ReactComponent as LogoIconSvg } from "./logo.svg";
import { ReactComponent as HomeIconSvg } from "./home.svg";
import { ReactComponent as NetworkIconSvg } from "./network.svg";
import { ReactComponent as ArrowRightIconSvg } from "./arrow-right.svg";
import { ReactComponent as ArticleIconSvg } from "./article.svg";
import { ReactComponent as CommentIconSvg } from "./comment.svg";
import { ReactComponent as EventIconSvg } from "./event.svg";
import { ReactComponent as PhotoIconSvg } from "./photo.svg";
import { ReactComponent as PlusIconSvg } from "./plus.svg";
import { ReactComponent as SendIconSvg } from "./send.svg";
import { ReactComponent as ShareIconSvg } from "./share.svg";
import { ReactComponent as VideoIconSvg } from "./video.svg";
import { ReactComponent as SidebarHeadIconSvg } from "./sidebar-head.svg";
import { ReactComponent as LikeIconSvg } from "./like.svg";
import { ReactComponent as LikedIconSvg } from "./liked.svg";
import { ReactComponent as LogoutIconSvg } from "./logout.svg";

import { createIcon } from "./Icon";

export const PersonIcon = createIcon(<PersonIconSvg />);
export const SearchIcon = createIcon(<SearchIconSvg />);
export const NotificationsIcon = createIcon(<NotificationsIconSvg />);
export const ChatIcon = createIcon(<ChatIconSvg />);
export const MoreVertIcon = createIcon(<MoreVertIconSvg />);
export const NetworkIcon = createIcon(<NetworkIconSvg />);
export const HomeIcon = createIcon(<HomeIconSvg />);
export const LogoIcon = createIcon(<LogoIconSvg />);
export const SidebarHeadIcon = createIcon(<SidebarHeadIconSvg />);
export const ArrowRightIcon = createIcon(<ArrowRightIconSvg />);
export const ArticleIcon = createIcon(<ArticleIconSvg />);
export const CommentIcon = createIcon(<CommentIconSvg />);
export const EventIcon = createIcon(<EventIconSvg />);
export const PhotoIcon = createIcon(<PhotoIconSvg />);
export const PlusIcon = createIcon(<PlusIconSvg />);
export const SendIcon = createIcon(<SendIconSvg />);
export const ShareIcon = createIcon(<ShareIconSvg />);
export const VideoIcon = createIcon(<VideoIconSvg />);
export const LikeIcon = createIcon(<LikeIconSvg />);
export const LikedIcon = createIcon(<LikedIconSvg />);
export const LogoutIcon = createIcon(<LogoutIconSvg />);
